// Long-form teaching content: the Materials Codex, cargo explainer, glossary, discussion
// prompts and sources. Values are typical/indicative (see docs/ for references).

export const CODEX = {
  ti: {
    overview: 'Ti-6Al-4V ("Ti-6-4", Grade 5) is about half of all titanium used. Aluminium stabilises the HCP α phase, vanadium stabilises the BCC β phase, giving a two-phase α+β alloy that can be heat-treated and forged to tailor its microstructure.',
    microstructure: 'α (HCP) + β (BCC). Mill-annealed material has fine, equiaxed α grains — good for resisting fatigue-crack initiation. β-annealed material has coarse lamellar ("Widmanstätten" or basket-weave) α colonies — the crack has to zig-zag between lamellae, so crack growth is slower and toughness higher, but high-cycle fatigue strength is lower.',
    processing: 'Ore → TiCl₄ → Kroll process (Mg reduction, slow batch) → sponge → vacuum-arc remelting → forging/rolling in the α+β field → mill anneal, STA or β anneal. Increasingly made by additive manufacturing (as-built α′ martensite, usually hot isostatically pressed to close porosity). Poor thermal conductivity makes machining slow, and buy-to-fly ratios of 10:1 are common.',
    uses: ['SR-71 Blackbird (≈90% titanium by structural weight)', 'Boeing 787 (≈15% by weight — compatible with CFRP)', 'Landing-gear beams, engine fan blades and discs, fasteners', 'Medical implants and cryogenic pressure vessels (ELI grade)'],
    pros: ['Highest specific strength of the metals here', 'Useful strength to ≈400 °C', 'Outstanding corrosion resistance (TiO₂ passive film)', 'Galvanically compatible and CTE-matched with CFRP'],
    cons: ['Expensive: Kroll process, vacuum melting, slow machining', 'Galls and cold-welds on sliding contact', 'Low thermal conductivity → hot spots and thermal distortion', 'Picks up oxygen (brittle α-case) above ≈500 °C; notch-sensitive in fatigue'],
    selection: 'Choose Ti when strength, temperature and corrosion all matter at once and cost does not — hot structure, highly loaded fittings, parts touching CFRP.',
    sustainability: 'High embodied energy (≈35–45 kg CO₂e/kg) from the Kroll process. Scrap is valuable and recycled, but must be kept free of contamination.',
  },
  al: {
    overview: '7075 is an Al-Zn-Mg-Cu alloy, the strongest widely used aluminium alloy. It was developed in Japan (Sumitomo "Extra Super Duralumin", used in the A6M Zero) and it is still standard for highly loaded aircraft parts such as upper wing skins and spar caps.',
    microstructure: 'FCC aluminium strengthened by nanometre precipitates. In T6 (peak-aged) the main strengthener is the metastable η′ phase (related to MgZn₂). Over-ageing (T73) grows coarser, stable η: slightly weaker, but far more resistant to stress-corrosion cracking and exfoliation.',
    processing: 'Cast → homogenise → hot roll/extrude/forge → solution treat ≈480 °C → water quench (supersaturated solid solution) → artificial age (T6 ≈120 °C/24 h; T73 two-step). Not fusion-weldable (hot cracking) — joined by rivets or friction-stir welding.',
    uses: ['Upper wing skins, stringers and spar caps', 'Fuselage frames and fittings', 'Bicycle components, climbing gear, mould tooling'],
    pros: ['Light and strong: σy/ρ ≈ 180 kN·m/kg', 'Cheap, well characterised and easy to machine', 'Very high thermal conductivity (≈130 W/m·K)', 'FCC — stays tough at cryogenic temperature'],
    cons: ['No true fatigue endurance limit; notch-sensitive', 'Loses its precipitation strengthening above ≈150 °C (over-ageing)', 'T6 is susceptible to stress-corrosion cracking and exfoliation', 'Cannot be fusion-welded'],
    selection: 'The balanced default for subsonic airframes — light, strong, cheap, repairable with riveted doublers — as long as it stays cool, dry and inspected for fatigue.',
    sustainability: 'Primary aluminium is energy-intensive (≈12 kg CO₂e/kg), but remelting scrap needs only ≈5% of that energy, so high recycled content transforms its footprint.',
  },
  ss: {
    overview: '316L is a molybdenum-bearing austenitic stainless steel (≈17% Cr, 12% Ni, 2.5% Mo) with low carbon (L ≤ 0.03%) to avoid sensitisation when welded. It is chosen for corrosion, heat and cryogenic service rather than for light weight.',
    microstructure: 'FCC austenite, stabilised at room temperature by nickel. No ductile-to-brittle transition. It cannot be hardened by heat treatment — only by cold work, which raises dislocation density and can form some strain-induced martensite.',
    processing: 'Electric-arc melting (largely from scrap) → AOD refining → casting → hot and cold rolling → solution anneal ≈1050 °C and rapid cool. Excellent weldability; also widely 3D-printed (laser powder-bed fusion).',
    uses: ['Chemical plant, marine fittings, food processing', 'Surgical implants (316LVM)', 'Cryogenic tanks and LNG equipment', 'SpaceX Starship uses related 300-series stainless (304L / "30X") for its cryogenic strength and heat tolerance'],
    pros: ['Very tough and ductile (≈50% elongation)', 'Keeps strength to ≈800 °C; oxidation-resistant', 'Tough and stronger at cryogenic temperature', 'Excellent corrosion resistance and weldability'],
    cons: ['Densest material here (8.0 g/cm³) with low annealed yield strength', 'Specific strength only ≈30 kN·m/kg annealed', 'Galls badly when self-mated', 'Low thermal conductivity → thermal distortion'],
    selection: 'Choose 316L where the environment, not the mass budget, is the hard constraint — hot, cold, corrosive or vacuum. As an airframe material it is a heavy insurance policy.',
    sustainability: 'Moderate embodied carbon (≈5–7 kg CO₂e/kg) with high recycled content; nickel and molybdenum make scrap valuable. Its weight, however, costs fuel every flight.',
  },
  cf: {
    overview: 'Carbon-fibre reinforced polymer is not a metal but a composite: stiff, strong carbon fibres (≈5–7 µm diameter) held in a polymer matrix. Its properties are designed ply by ply, so it is anisotropic — very strong along the fibres, weak across them.',
    microstructure: 'The "microstructure" is the laminate: fibre volume fraction (≈55–60%), ply orientations (e.g. a quasi-isotropic [0/±45/90]ₛ stack), void content and matrix chemistry. ±45° plies carry shear and torsion; 0° plies carry axial load. Interfaces between plies are the weak link (delamination).',
    processing: 'PAN precursor → oxidise and carbonise at 1000–3000 °C (energy-intensive) → fibre tow → impregnate with resin as prepreg → automated layup → vacuum bag → autoclave cure (≈180 °C, ≈7 bar for epoxy). Out-of-autoclave and thermoplastic routes are growing.',
    uses: ['Boeing 787 and Airbus A350 (≈50% of structural weight)', 'Formula 1 monocoques, bicycle frames', 'Satellite structures and telescope trusses (near-zero thermal expansion)', 'Rocket interstages and pressure vessels'],
    pros: ['Highest specific strength and stiffness here', 'Excellent tension–tension fatigue resistance', 'Does not corrode; stiffness can be tailored by layup', 'Near-zero thermal expansion along the fibres'],
    cons: ['Impact causes hidden delamination (barely visible impact damage)', 'Matrix limits temperature (epoxy Tg ≈180 °C) and absorbs moisture', 'Atomic oxygen and UV erode it in orbit; outgasses in vacuum', 'Hard to repair and inspect; galvanic corrosion of Al fasteners touching it'],
    selection: 'Choose CFRP when mass dominates the life-cycle (aircraft, spacecraft, racing) and you can afford the cost, the inspection regime and the temperature limit.',
    sustainability: 'High embodied energy (≈20–40 kg CO₂e/kg) and thermoset matrices cannot be remelted. Fuel saved over a long service life can repay the debt; end-of-life recycling is the open problem.',
  },
  mg: {
    overview: 'WE43 is a magnesium–yttrium–rare-earth (neodymium) alloy with zirconium grain refiner. At 1.84 g/cm³, magnesium is the lightest structural metal, and WE43 is one of the few Mg alloys with useful strength at 250 °C.',
    microstructure: 'HCP magnesium with Zr-refined grains and fine Y/Nd-rich precipitates after T6. HCP has few easy slip systems at room temperature, so deformation relies on basal slip and twinning — lower ductility, and tension–compression asymmetry in textured wrought products. Mg’s steep Hall–Petch slope makes grain refinement unusually effective.',
    processing: 'Cast (sand or investment) + T6 solution and age for creep-resistant housings; or extruded/forged for finer grains and higher strength. Melting needs protective cover gas. Coatings (plasma electrolytic oxidation, conversion coatings) are essential for corrosion protection.',
    uses: ['Helicopter transmission casings', 'Aircraft seat frames (FAA-accepted after flammability testing, from ≈2015)', 'Motorsport wheels and gearboxes', 'Bioresorbable medical implants (WE43-based)'],
    pros: ['Lowest density of any structural metal', 'Best metal for panel stiffness per kg (∛E/ρ)', 'Good creep strength to ≈250 °C for a light alloy', 'High damping capacity'],
    cons: ['The most anodic structural metal — corrodes readily, especially galvanically', 'Low ductility and toughness (K_IC ≈15 MPa√m)', 'HCP: limited low-temperature ductility', 'High vapour pressure (sublimation in hot vacuum); rare earths are costly'],
    selection: 'Choose Mg for stiffness-limited, moderately warm, well-protected parts where every gram counts and the environment is controlled.',
    sustainability: 'Primary Mg made by the Pidgeon (silicothermic) process is carbon-intensive (≈25–45 kg CO₂e/kg); electrolytic and recycled Mg are far lower. Rare-earth supply is geographically concentrated.',
  },
  cr: {
    overview: 'AISI 4130 ("chromoly") is a low-alloy steel with ≈1% Cr, 0.2% Mo and 0.3% C. It is cheap, tough and easily TIG-welded, which made it the classic material for tube-frame light aircraft, landing gear legs and race-car space frames.',
    microstructure: 'Normalised: fine ferrite (BCC) + pearlite. Quenched and tempered: tempered martensite — much stronger and with a lower ductile-to-brittle transition temperature. As a BCC steel it shows a true fatigue endurance limit, but it also shows a ductile-to-brittle transition at low temperature.',
    processing: 'Basic-oxygen or electric-arc steelmaking → hot rolling / tube drawing → normalise (≈870 °C, air cool) or quench (oil) and temper (≈200–650 °C). Welding destroys a Q&T heat treatment in the heat-affected zone, so welded frames are usually normalised.',
    uses: ['Piper J-3 Cub and Pitts fuselages, engine mounts', 'Landing-gear legs, roll cages, bicycle frames', 'Pressure-vessel and oil-tool components'],
    pros: ['Very cheap and universally available', 'Tough, ductile and field-weldable — the most repairable frame', 'True fatigue endurance limit', 'Keeps strength to ≈400 °C'],
    cons: ['Dense (7.85 g/cm³): low specific strength unless Q&T', 'Rusts — needs paint and internal tube protection', 'BCC: brittle below its transition temperature', 'High-strength tempers are prone to hydrogen embrittlement'],
    selection: 'Choose 4130 when cost, toughness and repairability matter more than mass — prototypes, small aircraft, rugged structures that must be fixed anywhere.',
    sustainability: 'Lowest embodied carbon here (≈2 kg CO₂e/kg, lower still from scrap via electric-arc furnaces) and the most recycled material on Earth — but its weight burns fuel every leg.',
  },
};

export const CARGO_TEXT = {
  title: 'Cargo: why it matters',
  points: [
    ['What it is', 'Crates of science payload and supplies for Station Meridian. Delivering them is the point of the mission.'],
    ['Why it scores', `Each crate you deliver intact is worth points — the largest single source of score.`],
    ['Why frames differ', 'A lighter structure leaves more of the maximum take-off mass for payload. That is why CFRP carries 6 crates and 316L only 3 — the payload fraction is a direct consequence of specific strength and stiffness.'],
    ['Load penalty', 'Cargo has mass. Every 2 crates aboard gives −1 on Strength and Fatigue checks (bigger loads per g and per gust) and each crate adds 0.5 h to every leg.'],
    ['Losing cargo', 'Some failures break crates loose, burn them or punch through the hold. A lost craft delivers nothing.'],
    ['Jettison', 'Before any roll you may dump a crate for +3 (Quartermaster +4): you lose its points but cut the load right now.'],
    ['Strategy', 'Load fully and you score more if you survive — but you fly slower and every strength and fatigue check gets harder. Fragile frames often do better with a lighter load.'],
  ],
};

export const SCORING = [
  ['Cargo delivered', 'points per crate (see Cargo)'],
  ['Airframe integrity', '+1 per integrity point left'],
  ['Mission complete', 'bonus for reaching the station intact'],
  ['Schedule', '+½ point per hour inside the 66 h docking window (−½ per hour late)'],
  ['Programme budget', 'cheaper frames leave budget unspent: 4130 +4, Al & 316L +3, Mg +2, Ti +1, CFRP 0'],
  ['Spare parts', '+1 per unused spare'],
  ['Engineering insight', '+1 per correct briefing answer'],
  ['Event bonuses', 'e.g. answering a distress call'],
  ['Green award', '+3 to the crew with the lowest life-cycle CO₂e per delivered crate'],
];

export const GLOSSARY = [
  ['Specific strength', 'Yield (or tensile) strength divided by density, σy/ρ. Governs the mass of strength-limited parts.'],
  ['Specific stiffness', 'Young’s modulus divided by density, E/ρ. Almost the same (≈25 GPa·cm³/g) for all common structural metals.'],
  ['Material index', 'A combination of properties to maximise for a given design (Ashby). E.g. √E/ρ for a light stiff beam, ∛E/ρ for a light stiff panel.'],
  ['Torsional stiffness', 'Resistance to twist, GJ (shear modulus × polar moment of area). At fixed mass, low density allows thicker walls and higher J.'],
  ['Endurance limit', 'Stress amplitude below which a material survives effectively infinite cycles. Shown by BCC steels and Ti alloys, not by Al or Mg alloys.'],
  ['S–N curve', 'Plot of stress amplitude against cycles to failure.'],
  ['Miner’s rule', 'Linear damage accumulation: failure when Σ(nᵢ/Nᵢ) = 1.'],
  ['Stress concentration (Kt)', 'Local stress ÷ nominal stress at a notch or hole. A round hole in a plate gives Kt ≈ 3.'],
  ['Fracture toughness (K_IC)', 'Resistance to crack propagation. Critical crack length a꜀ ≈ (1/π)(K_IC/Yσ)².'],
  ['Damage tolerance', 'Design philosophy that assumes flaws exist and sets inspection intervals so they are found before reaching a꜀.'],
  ['Precipitation hardening', 'Strengthening by fine particles that obstruct dislocations (e.g. η′ in 7075).'],
  ['Over-ageing', 'Precipitates coarsen with time at temperature; dislocations bypass them and strength falls.'],
  ['Solution treatment', 'Heating to dissolve alloying elements into a single solid solution before quenching.'],
  ['Martensite', 'Hard, metastable phase formed by rapid quenching of steel; tempering restores toughness.'],
  ['Normalising', 'Air cooling steel from the austenite region to produce fine, uniform ferrite + pearlite.'],
  ['Strain (work) hardening', 'Strength increase from plastic deformation, as dislocation density rises.'],
  ['Hall–Petch relation', 'σy = σ₀ + k·d^−½: finer grains are stronger. The slope k is large for Mg.'],
  ['Creep', 'Slow, time-dependent deformation under load at high homologous temperature.'],
  ['Glass transition (Tg)', 'Temperature at which a polymer softens from glassy to rubbery.'],
  ['Ductile-to-brittle transition', 'Change from ductile tearing to cleavage fracture as temperature falls — characteristic of BCC metals.'],
  ['Pilling–Bedworth ratio', 'Oxide volume ÷ metal volume consumed. ≈1–2 gives a protective film; <1 is porous (MgO), ≫2 tends to spall.'],
  ['Atomic oxygen (AO)', 'Dissociated oxygen in low Earth orbit that erodes polymers and carbon.'],
  ['Outgassing', 'Release of absorbed gases and volatiles in vacuum; screened by ASTM E595.'],
  ['Cold welding / galling', 'Adhesion and tearing of clean metal surfaces in contact, worst in vacuum.'],
  ['BVID', 'Barely visible impact damage — internal delamination in composites with little surface sign.'],
  ['Galvanic corrosion', 'Accelerated corrosion of the more anodic metal when two dissimilar conductors share an electrolyte.'],
  ['Embodied carbon', 'CO₂-equivalent emitted to produce a material (cradle-to-gate), per kg.'],
  ['Functional unit', 'The unit an LCA compares on — here, CO₂e per crate delivered, not per kg of material.'],
  ['DC (difficulty class)', 'The total you must reach on d20 + modifiers to succeed.'],
];

export const DISCUSSION = [
  'Which material would you actually choose for this mission, and would your answer change if the craft flew 500 missions instead of one?',
  'Specific stiffness is almost the same for Ti, Al, Mg and steel. So why do light alloys still win stiffness-limited designs?',
  'Your processing route changed your odds. Give one example where the same alloy, processed differently, would be the better choice.',
  'Which failures today were "hidden" until they were not? How does damage-tolerant design deal with that in real aircraft?',
  'The material with the best average score and the one that won most often may differ. What does that say about risk and reliability in engineering selection?',
  'CFRP saves fuel but is hard to recycle; 4130 is cheap and recyclable but heavy. Which matters more for an aircraft, and why?',
];

export const SOURCES = [
  'M. F. Ashby, Materials Selection in Mechanical Design, 5th ed., Butterworth-Heinemann, 2017 — material indices, selection charts.',
  'M. F. Ashby, Materials and the Environment, 2nd ed., Butterworth-Heinemann, 2013 — embodied energy and CO₂, eco-audits.',
  'W. D. Callister & D. G. Rethwisch, Materials Science and Engineering: An Introduction — fatigue, fracture, DBTT, precipitation hardening.',
  'I. J. Polmear et al., Light Alloys: Metallurgy of the Light Metals, 5th ed., 2017 — 7xxx tempers, Mg-RE alloys.',
  'G. Lütjering & J. C. Williams, Titanium, 2nd ed., Springer, 2007 — α+β microstructures and properties.',
  'ASM Handbook Vol. 1 (Properties of Irons and Steels) and Vol. 2 (Nonferrous Alloys); ASM Specialty Handbook: Stainless Steels.',
  'NASA Conference Publication 3134, LDEF — 69 Months in Space (1992) — atomic-oxygen and space-environment effects.',
  'ASTM E595 — Total Mass Loss and Collected Volatile Condensable Materials from Outgassing in a Vacuum Environment.',
  'NTSB Aircraft Accident Report AAR-89/03 — Aloha Airlines Flight 243 (multi-site fatigue damage).',
  'Typical property values from ASM/MatWeb datasheets (via ASM Aerospace Specification Metals) and the Luxfer MEL Technologies WE43B datasheet. Full Harvard reference list: see the project docs.',
];
