// Briefing questions. A correct answer gives +1 on that leg's roll (+2 for a Metallurgist).
// Leg 6 questions are specialist questions (+3) chosen by crew role.

export const QUESTIONS = {
  // ---- Leg 1: specific strength & stiffness
  q1a: { leg: 1, q: 'To make a tie rod of fixed length that carries a fixed load as LIGHT as possible, which property should be as high as possible?',
    options: ['Density ρ', 'Specific strength σy/ρ', 'Young’s modulus E'], answer: 1,
    explain: 'Mass = load × length × ρ/σy, so you maximise σy/ρ.' },
  q1b: { leg: 1, q: 'Specific stiffness (E/ρ) of titanium, aluminium, magnesium and steel is…',
    options: ['Highest for steel by far', 'Highest for magnesium by far', 'Roughly the same (≈25 GPa per g/cm³)'], answer: 2,
    explain: 'Almost all common structural metals have E/ρ ≈ 23–26. Only composites break away.' },
  q1c: { leg: 1, q: 'Why can a light-alloy tube resist twisting better than a steel tube of the SAME mass?',
    options: ['Lower density allows thicker walls / a larger section', 'Light alloys have a higher shear modulus', 'Steel is always weaker'], answer: 0,
    explain: 'G/ρ is similar for most metals; the win comes from geometry — thicker walls resist torsional buckling.' },
  q1d: { leg: 1, q: 'Cold-working 316L stainless steel raises its yield strength mainly by…',
    options: ['Forming fine precipitates', 'Increasing the dislocation density (strain hardening)', 'Growing larger grains'], answer: 1,
    explain: 'Austenitic stainless steels cannot be hardened by heat treatment — only by cold work.' },
  q1e: { leg: 1, q: 'For a flat panel that must not buckle at minimum mass, the material index ∛E/ρ favours…',
    options: ['Low-density materials such as Mg and CFRP', 'Dense, stiff steels', 'Whatever is cheapest'], answer: 0,
    explain: 'The cube root shrinks the modulus advantage, so density dominates.' },
  q1f: { leg: 1, q: 'Which of these has the highest specific strength?',
    options: ['Annealed 316L', 'Normalised 4130', 'CFRP'], answer: 2,
    explain: 'CFRP ≈ 400 kN·m/kg (quasi-isotropic), versus ≈ 58 for normalised 4130 and ≈ 30 for annealed 316L.' },

  // ---- Leg 2: fatigue
  q2a: { leg: 2, q: 'Which alloys typically show a true fatigue (endurance) limit?',
    options: ['Aluminium alloys', 'BCC steels and titanium alloys', 'Magnesium alloys'], answer: 1,
    explain: 'Below the endurance limit, steels and Ti alloys can survive effectively unlimited cycles. Al and Mg alloys cannot.' },
  q2b: { leg: 2, q: 'Fatigue cracks most often initiate…',
    options: ['At surface stress concentrations — holes, scratches, corners', 'In the centre of a smooth bar', 'Only in the weld metal'], answer: 0,
    explain: 'Stress concentrations and surface defects dominate crack initiation.' },
  q2c: { leg: 2, q: 'Shot peening improves fatigue life because it…',
    options: ['Roughens the surface', 'Removes all dislocations', 'Puts the surface into compressive residual stress'], answer: 2,
    explain: 'Compression at the surface holds crack faces shut.' },
  q2d: { leg: 2, q: 'Beach marks (clam-shell lines) on a fracture surface indicate…',
    options: ['Progressive fatigue crack growth', 'Brittle cleavage', 'Ductile overload'], answer: 0,
    explain: 'Each beach mark records a change in loading as the fatigue crack advanced.' },
  q2e: { leg: 2, q: 'Damage-tolerant design assumes that…',
    options: ['Parts never crack', 'Cracks exist, so inspect before they reach critical size', 'Only static loads matter'], answer: 1,
    explain: 'Inspection intervals are set from crack-growth rates and the critical crack size.' },
  q2f: { leg: 2, q: 'Critical crack length for fast fracture scales with…',
    options: ['(K_IC / σ)²', 'σ / K_IC', 'Density'], answer: 0,
    explain: 'From K = Yσ√(πa): a_c = (1/π)(K_IC / Yσ)². Tougher materials tolerate longer cracks.' },
  q2g: { leg: 2, q: 'The de Havilland Comet 1 losses (1954) were caused by…',
    options: ['Engine fires', 'Fatigue cracking from cut-out corners in the pressurised fuselage', 'Bird strikes'], answer: 1,
    explain: 'Pressurisation cycles grew fatigue cracks from stress concentrations at window and antenna cut-outs.' },

  // ---- Leg 3: probability & risk
  q3a: { leg: 3, q: 'You need 15 or more on a d20. What is your chance of success?',
    options: ['25%', '30%', '75%'], answer: 1,
    explain: 'Rolls 15–20 succeed: 6 of 20 faces = 30%.' },
  q3b: { leg: 3, q: 'Two independent 50% checks in a row. Chance that BOTH succeed?',
    options: ['25%', '50%', '100%'], answer: 0,
    explain: 'Independent probabilities multiply: 0.5 × 0.5 = 0.25.' },
  q3c: { leg: 3, q: 'In engineering, risk is usually defined as…',
    options: ['Probability only', 'Consequence only', 'Probability × consequence'], answer: 2,
    explain: 'A rare catastrophe and a frequent nuisance can carry similar risk.' },
  q3d: { leg: 3, q: 'A +3 modifier on a d20 roll changes your success chance by…',
    options: ['3 percentage points', '15 percentage points', '30 percentage points'], answer: 1,
    explain: 'Each +1 is one more face out of twenty: 5 percentage points.' },
  q3e: { leg: 3, q: 'A gamble: 50% chance to save 4 h, 50% chance to lose 2 h. Expected time change?',
    options: ['Save 1 h', 'Save 4 h', 'Lose 1 h'], answer: 0,
    explain: '0.5 × (−4) + 0.5 × (+2) = −1 h on average.' },

  // ---- Leg 4: thermal behaviour
  q4a: { leg: 4, q: 'Why was the SR-71 Blackbird built mostly from titanium rather than aluminium?',
    options: ['Titanium was cheaper', 'Aluminium alloys lose their precipitation strength at its ≈300 °C skin temperatures', 'Aluminium is too stiff'], answer: 1,
    explain: 'Precipitate coarsening (over-ageing) would have permanently softened an aluminium airframe.' },
  q4b: { leg: 4, q: '"Over-ageing" of 7075 at high temperature means…',
    options: ['Precipitates coarsen and strength drops permanently', 'The alloy melts', 'The grains become finer'], answer: 0,
    explain: 'Fine η′ precipitates grow into coarse η, which dislocations bypass easily.' },
  q4c: { leg: 4, q: 'The glass transition temperature (Tg) of a CFRP matrix is where…',
    options: ['The carbon fibres melt', 'The polymer softens from glassy to rubbery', 'The carbon oxidises'], answer: 1,
    explain: 'Above Tg the matrix can no longer support the fibres in compression or shear.' },
  q4d: { leg: 4, q: 'Resistance to thermal distortion is best for materials with a high…',
    options: ['Thermal expansion α', 'Density', 'Conductivity ÷ expansion (k/α)'], answer: 2,
    explain: 'High k evens out temperatures; low α limits the strain any gradient causes.' },
  q4e: { leg: 4, q: 'For creep resistance at high temperature you generally want…',
    options: ['Very fine grains', 'Coarse grains and thermally stable precipitates', 'Heavy cold work'], answer: 1,
    explain: 'Grain boundaries slide and act as diffusion paths at high temperature.' },
  q4f: { leg: 4, q: 'The thermal stress in a fully constrained bar heated by ΔT is about…',
    options: ['E α ΔT', 'E / (α ΔT)', 'α ΔT / E'], answer: 0,
    explain: 'The bar wants to expand by αΔT; constraint turns that strain into stress EαΔT.' },
  q4g: { leg: 4, q: 'WE43 magnesium keeps its strength to ≈250 °C mainly because…',
    options: ['It is really a composite', 'It has a BCC crystal structure', 'Rare-earth (Y, Nd) precipitates are thermally stable'], answer: 2,
    explain: 'Rare-earth precipitates resist coarsening far better than those in common Mg-Al alloys.' },

  // ---- Leg 5: vacuum & space
  q5a: { leg: 5, q: 'Which crystal structure typically shows a ductile-to-brittle transition at low temperature?',
    options: ['BCC (e.g. ferritic steels)', 'FCC (e.g. aluminium, 316L)', 'None — all metals stay ductile'], answer: 0,
    explain: 'In BCC metals the stress to move dislocations rises steeply as temperature falls, so cleavage takes over.' },
  q5b: { leg: 5, q: 'Atomic oxygen in low Earth orbit is most damaging to…',
    options: ['Aluminium', 'Polymers and carbon composites', 'Stainless steel'], answer: 1,
    explain: 'AO reacts with carbon and hydrocarbons to form gases, eroding the surface away.' },
  q5c: { leg: 5, q: 'A Pilling–Bedworth ratio below 1 (as for MgO) means the oxide is…',
    options: ['Dense and protective', 'Porous and non-protective', 'In compression and spalling'], answer: 1,
    explain: 'The oxide occupies less volume than the metal it replaced, so it cannot cover the surface.' },
  q5d: { leg: 5, q: '"Cold welding" happens in space because…',
    options: ['Oxide films are not replenished, so clean metal surfaces bond', 'Space is very cold', 'The solar wind melts metal'], answer: 0,
    explain: 'On Earth, air instantly re-oxidises surfaces and keeps them apart.' },
  q5e: { leg: 5, q: 'Outgassing from a composite in vacuum is mainly…',
    options: ['Carbon fibres evaporating', 'Water and volatiles released from the polymer matrix', 'Metal sublimation'], answer: 1,
    explain: 'Hence low-outgassing resins (e.g. cyanate esters) and ASTM E595 screening.' },
  q5f: { leg: 5, q: 'Why are austenitic stainless steels used for cryogenic propellant tanks?',
    options: ['They are the lightest metals', 'They are not metallic', 'Their FCC structure stays tough at very low temperature'], answer: 2,
    explain: 'FCC metals have no ductile-to-brittle transition — and 300-series stainless gets stronger in the cold.' },
};

// Leg 6 specialist questions — several variants per role.
export const ROLE_QUESTIONS = {
  pilot: [
    { q: 'You are in the same orbit as the station, 50 km behind it. To catch up you should first…',
      options: ['Fire forwards to speed up', 'Fire backwards to drop into a lower, faster orbit', 'Do nothing — orbits converge'], answer: 1,
      explain: 'Lower orbits have shorter periods. Speeding up raises your orbit and makes you fall further behind.' },
    { q: 'Your docking roll succeeds on 11+ and your total modifier is +3. Your success chance is…',
      options: ['50%', '65%', '80%'], answer: 1,
      explain: 'You need 8+ on the d20: faces 8–20 are 13 of 20 = 65%.' },
  ],
  structural: [
    { q: 'A part with a yield strength of 500 MPa carries 250 MPa. Its safety factor on yield is…',
      options: ['0.5', '2.0', '250'], answer: 1,
      explain: 'Safety factor = strength ÷ applied stress = 500 / 250 = 2.' },
    { q: 'A "fail-safe" structure is one that…',
      options: ['Can never fail', 'Has redundant load paths, so one failed member does not cause collapse', 'Is made from the strongest material'], answer: 1,
      explain: 'Fail-safe design, along with damage tolerance, is the backbone of airworthiness.' },
  ],
  metallurgist: [
    { q: 'The strut’s fracture shows smooth beach marks spreading from a corner, then a small rough final zone. Failure mode?',
      options: ['Ductile overload', 'Fatigue', 'Brittle cleavage'], answer: 1,
      explain: 'Beach marks record progressive crack growth; the rough zone is the final fast fracture.' },
    { q: 'The fracture is grey and fibrous with a cup-and-cone shape and obvious necking. Failure mode?',
      options: ['Ductile overload', 'Fatigue', 'Hydrogen embrittlement'], answer: 0,
      explain: 'Microvoid coalescence and necking mean the part was simply overloaded.' },
    { q: 'The fracture is flat, bright and glittery with river patterns, and it broke in the cold. Failure mode?',
      options: ['Creep', 'Ductile overload', 'Brittle cleavage'], answer: 2,
      explain: 'Cleavage facets — classic for a BCC steel below its transition temperature.' },
    { q: 'Cracks follow grain boundaries in a stressed part exposed to salt spray. Failure mode?',
      options: ['Stress-corrosion cracking', 'Fatigue', 'Ductile overload'], answer: 0,
      explain: 'Intergranular cracking under sustained stress plus a corrosive environment is SCC.' },
  ],
  ndt: [
    { q: 'You need to find a SUBSURFACE crack deep in a thick aluminium weld. Best method?',
      options: ['Dye penetrant', 'Ultrasonic testing', 'Visual inspection'], answer: 1,
      explain: 'Ultrasound reflects from internal flaws; dye penetrant only finds surface-breaking cracks.' },
    { q: 'You must check a non-magnetic austenitic stainless weld for SURFACE cracks. Which will NOT work?',
      options: ['Magnetic particle inspection', 'Dye penetrant', 'Eddy current'], answer: 0,
      explain: 'Magnetic particle inspection needs a ferromagnetic material; austenite is not.' },
    { q: 'You need to find cracks around fastener holes in a painted aluminium skin without stripping the paint. Best method?',
      options: ['Dye penetrant', 'Eddy current', 'Magnetic particle'], answer: 1,
      explain: 'Eddy currents pass through thin paint and are very sensitive to cracks in conductive metals.' },
    { q: 'You suspect gas porosity inside a casting. Which method gives a picture of it?',
      options: ['Radiography (X-ray)', 'Dye penetrant', 'Hardness testing'], answer: 0,
      explain: 'Pores absorb less radiation and show up darker on the radiograph.' },
  ],
  coatings: [
    { q: 'A polymer seal is eroding under atomic oxygen. Best protection?',
      options: ['A thin SiO₂ (glassy) coating', 'A coat of oil', 'Paint it black'], answer: 0,
      explain: 'SiO₂ is already fully oxidised, so atomic oxygen cannot attack it.' },
    { q: 'A magnesium bracket is corroding where steel bolts pass through it. Best fix?',
      options: ['Use bigger steel bolts', 'Isolate the galvanic couple (coat the Mg, use sealant/washers)', 'Remove the paint'], answer: 1,
      explain: 'Mg is anodic to almost everything; break the electrical path and the electrolyte.' },
    { q: 'Stainless steel threads keep seizing in vacuum. Best fix?',
      options: ['A liquid oil', 'Nothing — it is unavoidable', 'A dry-film lubricant such as MoS₂'], answer: 2,
      explain: 'Oils evaporate in vacuum; lamellar solids such as MoS₂ keep surfaces apart.' },
  ],
  quartermaster: [
    { q: 'Maximum take-off weight is fixed. If the structure becomes 100 kg lighter, payload can rise by about…',
      options: ['10 kg', '100 kg', '1000 kg'], answer: 1,
      explain: 'For a fixed maximum mass, every kilogram of structure saved can be payload (or fuel).' },
    { q: 'Over an airliner’s life, which phase usually dominates its energy use and emissions?',
      options: ['Making the materials', 'Flying it (fuel burn)', 'Scrapping it'], answer: 1,
      explain: 'Use-phase fuel dominates — which is why lightweighting can justify high-embodied-energy materials.' },
  ],
};

export function questionById(id) {
  if (!id) return null;
  if (id.startsWith('r:')) {
    const [, role, idx] = id.split(':');
    return ROLE_QUESTIONS[role]?.[+idx] || null;
  }
  return QUESTIONS[id] || null;
}
